services:
  # Servizio di build per creare l'immagine personalizzata
  builder:
    image: manzolo-ca-alpine:latest  # Nome dell'immagine creata
    build:
      context: .  # Directory contenente il Dockerfile
      dockerfile: Dockerfile  # Nome del Dockerfile
    # Non avviare questo servizio, serve solo per costruire l'immagine
    restart: "no"
  root-ca:
    image: manzolo-ca-alpine:latest
    depends_on:
      - builder
    container_name: root-ca
    volumes:
      - ./config/openssl-root.cnf:/etc/ssl/openssl.cnf
      - ./scripts/openssl_scripts/root-ca/scripts:/scripts
      - ./data/root-ca:/${ROOT}
    environment:
      - C_ROOT=${C_ROOT}
      - ST_ROOT=${ST_ROOT}
      - L_ROOT=${L_ROOT}
      - O_ROOT=${O_ROOT}
      - OU_ROOT=${OU_ROOT}
      - ROOT=${ROOT}

  intermediate-ca:
    image: manzolo-ca-alpine:latest
    depends_on:
      - builder
    container_name: intermediate-ca
    volumes:
      - ./config/openssl-intermediate.cnf:/etc/ssl/openssl.cnf
      - ./scripts/openssl_scripts/intermediate-ca/scripts:/scripts
      - ./data/intermediate-ca:/${ROOT}
    environment:
      - C_INTERMEDIATE=${C_INTERMEDIATE}
      - ST_INTERMEDIATE=${ST_INTERMEDIATE}
      - L_INTERMEDIATE=${L_INTERMEDIATE}
      - O_INTERMEDIATE=${O_INTERMEDIATE}
      - OU_INTERMEDIATE=${OU_INTERMEDIATE}
      - ROOT=${ROOT}

  server-ca:
    image: manzolo-ca-alpine:latest
    depends_on:
      - builder
    container_name: server-ca
    environment:
      - C_SERVER=${C_SERVER}
      - ST_SERVER=${ST_SERVER}
      - L_SERVER=${L_SERVER}
      - O_SERVER=${O_SERVER}
      - OU_SERVER=${OU_SERVER}
      - ROOT=${ROOT}

    volumes:
      - ./config/openssl-server.cnf:/etc/ssl/openssl.cnf
      - ./scripts/openssl_scripts/server-ca/scripts:/scripts
      - ./data/server-ca:/${ROOT}
