services:
  root-ca:
    image: alpine:latest
    container_name: root-ca
    volumes:
      - ./config/openssl-root.cnf:/etc/ssl/openssl.cnf
      - ./root-ca/scripts:/scripts
      - ./shared-data/root-ca:/manzoloCA
    environment:
      - C_ROOT=${C_ROOT}
      - ST_ROOT=${ST_ROOT}
      - L_ROOT=${L_ROOT}
      - O_ROOT=${O_ROOT}
      - OU_ROOT=${OU_ROOT}
      - CN_ROOT=${CN_ROOT}
      - EMAIL_ROOT=${EMAIL_ROOT}
      - PASSWORD_ROOT=${PASSWORD_ROOT}

    #entrypoint: ["/scripts/init-root-ca.sh"]

  intermediate-ca:
    image: alpine:latest
    container_name: intermediate-ca
    volumes:
      - ./config/openssl-intermediate.cnf:/etc/ssl/openssl.cnf
      - ./intermediate-ca/scripts:/scripts
      - ./shared-data/intermediate-ca:/manzoloCA
    environment:
      - CN_INTERMEDIATE=${CN_INTERMEDIATE}
      - EMAIL_INTERMEDIATE=${EMAIL_INTERMEDIATE}
      - C_INTERMEDIATE=${C_INTERMEDIATE}
      - ST_INTERMEDIATE=${ST_INTERMEDIATE}
      - L_INTERMEDIATE=${L_INTERMEDIATE}
      - O_INTERMEDIATE=${O_INTERMEDIATE}
      - OU_INTERMEDIATE=${OU_INTERMEDIATE}
      - CN_INTERMEDIATE=${CN_INTERMEDIATE}
      - EMAIL_INTERMEDIATE=${EMAIL_INTERMEDIATE}
      - CN_SERVER=${CN_SERVER}
      - PASSWORD_INTERMEDIATE=${PASSWORD_INTERMEDIATE}
    #entrypoint: ["/scripts/init-intermediate-ca.sh"]

  server-ca:
    image: alpine:latest
    container_name: server-ca
    environment:
      - C_SERVER=${C_SERVER}
      - ST_SERVER=${ST_SERVER}
      - L_SERVER=${L_SERVER}
      - O_SERVER=${O_SERVER}
      - OU_SERVER=${OU_SERVER}
      - CN_SERVER=${CN_SERVER}
      - EMAIL_SERVER=${EMAIL_SERVER}
      - PASSWORD_SERVER=${PASSWORD_SERVER}

    volumes:
      - ./config/openssl-server.cnf:/etc/ssl/openssl.cnf
      - ./server-ca/scripts:/scripts
      - ./shared-data/server-ca:/manzoloCA
    #entrypoint: ["/scripts/init-server-ca.sh"]