services:
  root-ca:
    image: alpine:latest
    container_name: root-ca
    volumes:
      - ./config/openssl-root.cnf:/etc/ssl/openssl.cnf
      - ./root-ca/scripts:/scripts
      - ./shared-data/root-ca:/manzoloCA
    entrypoint: ["/scripts/init-root-ca.sh"]

  intermediate-ca:
    image: alpine:latest
    container_name: intermediate-ca
    volumes:
      - ./config/openssl-intermediate.cnf:/etc/ssl/openssl.cnf
      - ./intermediate-ca/scripts:/scripts
      - ./shared-data/root-ca:/manzoloCA
      - ./shared-data/intermediate-ca:/manzoloCA/intermediate
    environment:
      - CN=${CN}
      - EMAIL=${EMAIL}
      - C_INTERMEDIATE1=${C_INTERMEDIATE1}
      - ST_INTERMEDIATE1=${ST_INTERMEDIATE1}
      - L_INTERMEDIATE1=${L_INTERMEDIATE1}
      - O_INTERMEDIATE1=${O_INTERMEDIATE1}
      - OU_INTERMEDIATE1=${OU_INTERMEDIATE1}
      - CN_INTERMEDIATE1=${CN_INTERMEDIATE1}
      - EMAIL_INTERMEDIATE1=${EMAIL_INTERMEDIATE1}
    entrypoint: ["/scripts/init-intermediate-ca.sh"]

  server-ca:
    image: alpine:latest
    container_name: server-ca
    environment:
      - CN=${CN}
      - EMAIL=${EMAIL}
      - C_INTERMEDIATE1=${C_INTERMEDIATE1}
      - ST_INTERMEDIATE1=${ST_INTERMEDIATE1}
      - L_INTERMEDIATE1=${L_INTERMEDIATE1}
      - O_INTERMEDIATE1=${O_INTERMEDIATE1}
      - OU_INTERMEDIATE1=${OU_INTERMEDIATE1}
      - CN_INTERMEDIATE1=${CN_INTERMEDIATE1}
      - EMAIL_INTERMEDIATE1=${EMAIL_INTERMEDIATE1}      
    volumes:
      - ./config/openssl-server.cnf:/etc/ssl/openssl.cnf
      - ./server-ca/scripts:/scripts
      - ./shared-data/intermediate-ca:/manzoloCA/intermediate
      - ./shared-data/server-ca:/manzoloCA/server
    entrypoint: ["/scripts/init-server-ca.sh"]